version: "2"
linters:
  default: all
  disable:
    - noctx
    - wsl
    - wsl_v5
    - embeddedstructfieldcheck
    - noinlineerr
    - varnamelen
    - gocognit
    - funlen
    - cyclop
    - revive
    - nestif
    - mnd
    - gochecknoglobals
    - exhaustruct
    - wrapcheck
    - testpackage
    - tagliatelle
    - nlreturn
    - depguard
    - dupl
    - err113
    - forbidigo
    - errname
    - forcetypeassert
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - gosmopolitan
    - lll
    - paralleltest
    - unparam
    - maintidx
    - nonamedreturns
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1001'
        - '-ST1003'
        - '-QF1001'
        - '-QF1003'
    gosec:
      excludes:
        - G115
        - G204
        - G301
        - G304
        - G306
        - G404
        - G602 # There is a false positive in golangci-lint. Waiting for being fixed.
run:
  timeout: 3m
