version: "2"
linters:
  default: all
  disable:
    - noctx
    - wsl
    - wsl_v5
    - embeddedstructfieldcheck
    - noinlineerr
    - varnamelen
    - gocognit
    - funlen
    - cyclop
    - nestif
    - mnd
    - gochecknoglobals
    - exhaustruct
    - wrapcheck
    - testpackage
    - tagliatelle
    - nlreturn
    - depguard
    - dupl
    - err113
    - forbidigo
    - errname
    - forcetypeassert
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - gosmopolitan
    - lll
    - paralleltest
    - unparam
    - maintidx
    - nonamedreturns
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1001'
        - '-ST1003'
        - '-QF1001'
        - '-QF1003'
    gosec:
      excludes:
        - G115
        - G204
        - G301
        - G304
        - G306
        - G404
    revive:
      enable-all-rules: true
      rules:
        - name: dot-imports
          disabled: true
        - name: add-constant
          disabled: true
        - name: line-length-limit
          arguments: [128]
        - name: cognitive-complexity
          arguments: [25]
        - name: function-length
          arguments: [200, 0]
        - name: cyclomatic
          arguments: [20]
        - name: exported
          arguments: ["disable-checks-on-methods"]
        - name: function-result-limit
          arguments: [4]
run:
  timeout: 3m
